"""update campaigns table for college outreach

Revision ID: 2e39fae3a26c
Revises: 427a16180ca1
Create Date: 2026-09-03 13:43:25.492366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e39fae3a26c'
down_revision: Union[str, Sequence[str], None] = '427a16180ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('college_id', sa.Integer(), nullable=False))
    op.add_column('campaigns', sa.Column('campaign_type', sa.String(length=50), nullable=False))
    op.add_column('campaigns', sa.Column('message_type', sa.String(length=50), nullable=False))
    op.add_column('campaigns', sa.Column('channel', sa.String(length=50), nullable=False))
    op.add_column('campaigns', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('campaigns', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('campaigns', sa.Column('priority', sa.String(length=50), nullable=False))
    op.add_column('campaigns', sa.Column('required_approval', sa.Boolean(), nullable=False))
    op.add_column('campaigns', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('campaigns_organization_id_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(
        'campaigns_college_id_fkey',
        'campaigns',
        'colleges',
        ['college_id'],
        ['id'],
    )
    op.drop_column('campaigns', 'name')
    op.drop_column('campaigns', 'updated_at')
    op.drop_column('campaigns', 'description')
    op.drop_column('campaigns', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_organization_id_fkey'), 'campaigns', 'organizations', ['organization_id'], ['id'])
    op.alter_column('campaigns', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('campaigns', 'approved_at')
    op.drop_column('campaigns', 'required_approval')
    op.drop_column('campaigns', 'priority')
    op.drop_column('campaigns', 'message')
    op.drop_column('campaigns', 'subject')
    op.drop_column('campaigns', 'channel')
    op.drop_column('campaigns', 'message_type')
    op.drop_column('campaigns', 'campaign_type')
    op.drop_column('campaigns', 'college_id')
    # ### end Alembic commands ###
