"""update colleges enrichment fields

Revision ID: 36fa53e84f9c
Revises: 92acad48771e
Create Date: 2026-09-03 11:40:54.141117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36fa53e84f9c'
down_revision: Union[str, Sequence[str], None] = '92acad48771e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colleges', sa.Column('official_email', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('colleges', sa.Column('official_phone', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('colleges', sa.Column('contact_role', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('colleges', sa.Column('contact_form', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('colleges', sa.Column('whatsapp', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('colleges', sa.Column('linkedin', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('colleges', sa.Column('training', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('colleges', sa.Column('workshop_training_opportunity', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('colleges', sa.Column('placement_available', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('colleges', 'email')
    op.drop_column('colleges', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colleges', sa.Column('phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('colleges', 'placement_available')
    op.drop_column('colleges', 'workshop_training_opportunity')
    op.drop_column('colleges', 'training')
    op.drop_column('colleges', 'linkedin')
    op.drop_column('colleges', 'whatsapp')
    op.drop_column('colleges', 'contact_form')
    op.drop_column('colleges', 'contact_role')
    op.drop_column('colleges', 'official_phone')
    op.drop_column('colleges', 'official_email')
    # ### end Alembic commands ###
