"""add contact updated to campaigns

Revision ID: 69470fab03be
Revises: 7807b269576b
Create Date: 2026-09-28 08:16:30.708661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69470fab03be'
down_revision: Union[str, Sequence[str], None] = '7807b269576b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "campaigns",
        sa.Column(
            "contact_updated",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'contact_updated')
    # ### end Alembic commands ###
