"""add call confirmation timestamp

Revision ID: 7807b269576b
Revises: 883286661f17
Create Date: 2026-09-25 09:47:20.548951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7807b269576b'
down_revision: Union[str, Sequence[str], None] = '883286661f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_calls', sa.Column('confirmation_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_calls', 'confirmation_sent_at')
    # ### end Alembic commands ###
