"""add workflow runs and update agent runs

Revision ID: 83bbe12af05d
Revises: 7b1c9e4a21f3
Create Date: 2026-09-07 12:37:35.353403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83bbe12af05d'
down_revision: Union[str, Sequence[str], None] = '7b1c9e4a21f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_runs', sa.Column('workflow_id', sa.Integer(), nullable=False))
    op.add_column('agent_runs', sa.Column('result', sa.Text(), nullable=True))
    op.add_column('agent_runs', sa.Column('error', sa.Text(), nullable=True))
    op.alter_column('agent_runs', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('agent_runs_campaign_id_fkey'), 'agent_runs', type_='foreignkey')
    op.create_foreign_key(None, 'agent_runs', 'workflow_runs', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agent_runs', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.create_foreign_key(op.f('agent_runs_campaign_id_fkey'), 'agent_runs', 'campaigns', ['campaign_id'], ['id'])
    op.alter_column('agent_runs', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('agent_runs', 'error')
    op.drop_column('agent_runs', 'result')
    op.drop_column('agent_runs', 'workflow_id')
    op.drop_table('workflow_runs')
    # ### end Alembic commands ###
