"""add AP colleges table

Revision ID: 92acad48771e
Revises: 7ef8eb1082bd
Create Date: 2026-08-27 12:02:18.182041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92acad48771e'
down_revision: Union[str, Sequence[str], None] = '7ef8eb1082bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('departments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('programs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_ml_related', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generative_ai_related', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agentic_ai_related', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('placement_page', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contact_page', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('innovation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entrepreneurship', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clubs_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colleges')
    # ### end Alembic commands ###
